# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feeder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeder_name', models.CharField(max_length=255)),
                ('lat', models.CharField(max_length=50)),
                ('long', models.CharField(max_length=50)),
                ('created_by', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feederdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twlon_time', models.CharField(max_length=20)),
                ('dimon_time', models.CharField(max_length=20)),
                ('dimoff_time', models.CharField(max_length=20)),
                ('twloff_time', models.CharField(max_length=20)),
                ('auto_mode', models.BooleanField(default=False)),
                ('man_mode', models.BooleanField(default=False)),
                ('date_filed', models.DateTimeField()),
                ('r_voltage', models.CharField(max_length=20)),
                ('r_current', models.CharField(max_length=20)),
                ('r_frequency', models.CharField(max_length=20)),
                ('r_pf', models.CharField(max_length=20)),
                ('r_ac', models.CharField(max_length=20)),
                ('r_app', models.CharField(max_length=20)),
                ('r_ph_rotio', models.CharField(max_length=20)),
                ('r_on', models.CharField(max_length=20)),
                ('r_off', models.CharField(max_length=20)),
                ('r_vf', models.CharField(max_length=20)),
                ('r_cf', models.CharField(max_length=20)),
                ('r_ff', models.CharField(max_length=20)),
                ('y_voltage', models.CharField(max_length=20)),
                ('y_current', models.CharField(max_length=20)),
                ('y_frequency', models.CharField(max_length=20)),
                ('y_pf', models.CharField(max_length=20)),
                ('y_ac', models.CharField(max_length=20)),
                ('y_app', models.CharField(max_length=20)),
                ('y_ph_rotio', models.CharField(max_length=20)),
                ('y_on', models.CharField(max_length=20)),
                ('y_off', models.CharField(max_length=20)),
                ('y_vf', models.CharField(max_length=20)),
                ('y_cf', models.CharField(max_length=20)),
                ('y_ff', models.CharField(max_length=20)),
                ('b_voltage', models.CharField(max_length=20)),
                ('b_current', models.CharField(max_length=20)),
                ('b_frequency', models.CharField(max_length=20)),
                ('b_pf', models.CharField(max_length=20)),
                ('b_ac', models.CharField(max_length=20)),
                ('b_app', models.CharField(max_length=20)),
                ('b_ph_rotio', models.CharField(max_length=20)),
                ('b_on', models.CharField(max_length=20)),
                ('b_off', models.CharField(max_length=20)),
                ('b_vf', models.CharField(max_length=20)),
                ('b_cf', models.CharField(max_length=20)),
                ('b_ff', models.CharField(max_length=20)),
                ('dof', models.CharField(max_length=20)),
                ('created_by', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmc.Feeder')),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdivision_name', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmc.Division')),
            ],
        ),
        migrations.AddField(
            model_name='feeder',
            name='subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmc.Subdivision'),
        ),
    ]
