# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0002_auto_20170503_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feederdata',
            old_name='b_ac',
            new_name='b_ap',
        ),
        migrations.RenameField(
            model_name='feederdata',
            old_name='r_ac',
            new_name='r_ap',
        ),
        migrations.RenameField(
            model_name='feederdata',
            old_name='y_ac',
            new_name='y_ap',
        ),
        migrations.AlterField(
            model_name='feederdata',
            name='b_cf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feederdata',
            name='b_ff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feederdata',
            name='b_vf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feederdata',
            name='dof',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feederdata',
            name='r_cf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feederdata',
            name='r_ff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feederdata',
            name='r_vf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feederdata',
            name='y_cf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feederdata',
            name='y_ff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feederdata',
            name='y_vf',
            field=models.BooleanField(default=False),
        ),
    ]
