# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0004_auto_20170504_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feederdata',
            name='spare_field1',
        ),
        migrations.AddField(
            model_name='feederdata',
            name='dimming_percent',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
