# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 06:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pmc', '0006_auto_20170506_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alaram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_type', models.CharField(max_length=255)),
                ('number_1', models.CharField(max_length=20)),
                ('number_2', models.CharField(max_length=20)),
                ('number_3', models.CharField(max_length=20)),
                ('number_4', models.CharField(max_length=20)),
                ('number_5', models.CharField(max_length=20)),
                ('number_6', models.CharField(max_length=20)),
                ('feeder_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmc.Feederdata')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.CharField(max_length=255)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
