# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0007_alaram_userdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alaram',
            old_name='feeder_data',
            new_name='feederdata',
        ),
    ]
