# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0008_auto_20170509_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeder',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='feeder',
            old_name='long',
            new_name='longitude',
        ),
    ]
