# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0009_auto_20170509_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alaram',
            name='number_1',
            field=models.CharField(default=b'0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='alaram',
            name='number_2',
            field=models.CharField(default=b'0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='alaram',
            name='number_3',
            field=models.CharField(default=b'0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='alaram',
            name='number_4',
            field=models.CharField(default=b'0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='alaram',
            name='number_5',
            field=models.CharField(default=b'0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='alaram',
            name='number_6',
            field=models.CharField(default=b'0000000000', max_length=20),
        ),
    ]
