# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0011_auto_20170509_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeder',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
