# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0012_auto_20170509_1315'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alaram',
            new_name='Alarm',
        ),
    ]
