# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0013_auto_20170511_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
