# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0014_userdata_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feederdata',
            name='spare_field2',
        ),
        migrations.AddField(
            model_name='feederdata',
            name='signal_strength',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
