# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0015_auto_20170516_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feederdata',
            name='signal_strength',
            field=models.IntegerField(choices=[(0, b'No Signal'), (25, b'Weak'), (75, b'Good'), (100, b'Strong')], default=0),
        ),
    ]
