# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0016_auto_20170516_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendToClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=20)),
                ('output_code', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_send', models.BooleanField(default=False)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmc.Feeder')),
            ],
        ),
    ]
