# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0017_sendtoclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feederdata',
            name='signal_strength',
            field=models.CharField(choices=[(b'N', b'No Signal'), (b'W', b'Weak'), (b'G', b'Good'), (b'S', b'Strong')], default=b'N', max_length=10),
        ),
    ]
