# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0019_errorlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='role',
        ),
        migrations.AddField(
            model_name='userdata',
            name='role_division',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='role_subdivision',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
