# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-13 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmc', '0021_sendtoclient_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='fault_occur',
            field=models.BooleanField(default=False),
        ),
    ]
